apiVersion: apps/v1
kind: Deployment
metadata:
  name: focus-deployment
  labels:
    app: web
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: focus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: focus
    spec:
      containers:
      - image: gcr.io/vigilant-walker-327408/github.com/wojtekkw10/focus:137919a
        imagePullPolicy: IfNotPresent
        name: focus-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 20