apiVersion: apps/v1
kind: Deployment
metadata:
  name: focus-deployment
  labels:
    app: web
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: focus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: focus
    spec:
      containers:
      - image: gcr.io/vigilant-walker-327408/github.com/wojtekkw10/focus:137919a
        imagePullPolicy: IfNotPresent
        name: focus-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 20
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2021-09-28T14:14:55Z"
    lastUpdateTime: "2021-09-28T14:14:55Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-09-28T14:14:40Z"
    lastUpdateTime: "2021-09-28T14:14:55Z"
    message: ReplicaSet "focus-7ffb9d669b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
